### ISSUE TITLE
[Feature] Implement call throttling

### ISSUE THREAD

**Issue by quetzyg** [tiagojpdias/pepe-as-a-service#3]
**Problem:**
Currently, users can invoke the bot as many times as they want, causing a flood if the command is abused.

**Solution:**
Implement a throttling mechanism so that each user has to wait N seconds until the bot stops ignoring him.

**Workflow:**

1. A user invokes the bot for the first time;
2. The bot records the user, the current timestamp and sends a random image;
3. The same user invokes the bot again;
4. The bot checks if there's a record of the user;
5. If so, it then checks if N seconds have passed since the last invocation;
6. If true, a random image is sent and the timestamp gets updated;
7. If not, the user is ignored;

**Comment by tiagojpdias** [comment]
Feature added at PR https://github.com/tiagojpdias/pepe-as-a-service/pull/7
